[package]
name = "rust_hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenvy = "0.15"
sdl2 = { version = "0.35", features = ["ttf"] }
urlencoding = "2.1"
