scrape_configs:
  - job_name: 'dashboard_service'
    static_configs:
      - targets: ['dashboard_local:8085']
    metrics_path: /metrics
  - job_name: 'finance_service'
    static_configs:
      - targets: ['finance_tracker-finance-1:4000', 'finance_tracker-finance:4000', 'finance_local:4000']
    metrics_path: /metrics

  - job_name: 'local_services'
    static_configs:
      - targets: ['localhost:4000', 'localhost:8086']
    metrics_path: /metrics

  - job_name: 'backend'
    static_configs:
      - targets: ['localhost:8080']
    # Spring Boot / Micrometer typically exposes Prometheus metrics at /actuator/prometheus
    metrics_path: /actuator/prometheus

  - job_name: 'helpsite'
    static_configs:
      - targets: ['localhost:8001']
    metrics_path: /metrics
